services:
  arsenal-db:
    image: timescale/timescaledb:latest-pg14
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: arsenal_db
    ports:
      - "5432:5432"
    volumes:
      - arsenal_db_data:/var/lib/postgresql/data

  arsenal-app:
    build: .
    restart: unless-stopped
    # --- CORRECTION V3.1 : 'command' est au même niveau que 'build' ---
    command: tail -f /dev/null
    volumes:
      - .:/app
    depends_on:
      - arsenal-db

volumes:
  arsenal_db_data:
